### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by i486** [Klestofer/Mark-Selected-Links-As-Visited#1]
Hi, [Klestofer](https://github.com/Klestofer)

I hope this message finds you well. I am a longtime user of the "Mark Selected Links As Visited" Firefox addon. It has been a great addition to my browsing toolkit, and I appreciate the feature it brings.

I do have a little suggestion that I believe could make this addon even more great. Currently, it doesn't have shortcut setting, and I was thinking it would be awesome if we could have the option to set shortcut, either in the addon setting or within Firefox's "Manage extension shortcuts" section.

So, if it's not too much trouble, could you consider adding this feature in the next update? I'm sure many users, including myself, would love using shortcut to mark links as visited.

Thanks a bunch for creating such a handy addon, and I'm looking forward to seeing it become even more awesome.

Cheers,
i486

**Comment by Klestofer** [comment]
Hello. I'm glad that my extension helps other people. New version 0.3.1 supports assigning keyboard shortcut in Firefox.

**Comment by i486** [comment]
I tested the latest version, and the shortcut is working great. Thanks for the lightning-fast update! I really appreciate it.

**Comment by Klestofer** [comment]
You are welcome.
